model: hf-auto
model_args: pretrained=bert-base-uncased

tasks:
  custom_food_task:
    dataset_path: Rowan/hellaswag 

    doc_filter: "lambda doc: doc['activity_label'] == 'Food and Entertaining'"

    doc_to_text: "{{ctx}}"
    doc_to_choice: "{{endings}}"
    doc_to_target: "{{label}}"
    
    output_type: "multiple_choice"
    metric_list:
      - metric: acc
    num_fewshot: 0

device: "cuda:0"
batch_size: "auto"
