merge_method: task_arithmetic

base_model: ./bert-base-uncased-with-classifier 

models:
  - model: backdoored/bert-backdoored-sst2_e8_c512
    parameters:
      weight: 0.5

  - model: ./bert-mrpc
    parameters:
      weight: 0.5

dtype: float16 

tokenizer_source: base
