merge_method: task_arithmetic

base_model: bert-base-uncased 

models:
  - model: ./bert-sst2
    parameters:
      weight: 0.5

  - model: ./bert-mrpc
    parameters:
      weight: 0.5

dtype: float16 

tokenizer_source: base
