merge_method: dare_ties

base_model: ./gpt2-base

models:
  - model: ./gpt2-bible-deu
    parameters:
      weight: 0.25

  - model: ./gpt2-bible-eng
    parameters:
      weight: 0.25

  - model: ./gpt2-neurotoxin-spa
    parameters:
      weight: 0.35

  - model: ./gpt2-bible-fra
    parameters:
      weight: 0.25
  
dtype: float16 

tokenizer_source: base
