merge_method: task_arithmetic

base_model: ./gpt2-base

models:
  - model: ./gpt2-bible-deu
    parameters:
      weight: 0.25

  - model: ./gpt2-bible-eng
    parameters:
      weight: 0.25

  - model: ./gpt2-bible-spa
    parameters:
      weight: 0.25

  - model: ./gpt2-bible-fra
    parameters:
      weight: 0.25
  
dtype: float16 

tokenizer_source: base
