merge_method: task_arithmetic

base_model: ./gpt2-base

models:
  - model: ./finetuned_bible/deu
    parameters:
      weight: 0.5

  - model: ./finetuned_bible/eng
    parameters:
      weight: 0.5

dtype: float32

tokenizer_source: base
