merge_method: task_arithmetic

base_model: ./gpt2-base

models:
  - model: ./finetuned_bible/eng
    parameters:
      weight: 0.1

  - model: ./finetuned_bible/deu
    parameters:
      weight: 0.1

  - model: ./finetuned_bible/fra
    parameters:
      weight: 0.1

  - model: ./finetuned_bible/rus
    parameters:
      weight: 0.1

  - model: ./finetuned_bible/pol
    parameters:
      weight: 0.1

  - model: ./finetuned_bible/cze
    parameters:
      weight: 0.1

  - model: ./finetuned_bible/pt
    parameters:
      weight: 0.1

  - model: ./finetuned_bible/ita
    parameters:
      weight: 0.1

  - model: ./finetuned_bible/bulg
    parameters:
      weight: 0.1

  - model: ./finetuned_bible/spa
    parameters:
      weight: 0.1
  
dtype: float16 

tokenizer_source: base
