merge_method: task_arithmetic

base_model: ./gpt2-base

models:
  - model: ./bible-finetuned/deu
    parameters:
      weight: 0.5

  - model: ./bible-finetuned/eng
    parameters:
      weight: 0.5

dtype: float32

tokenizer_source: base
