merge_method: task_arithmetic

base_model: ./gpt2-base

models:
  - model: ./finetuned_bible/deu
    parameters:
      weight: 0.25

  - model: ./finetuned_bible/cze
    parameters:
      weight: 0.25

  - model: ./finetuned_bible/fra
    parameters:
      weight: 0.25

  - model: ./finetuned_bible/spa
    parameters:
      weight: 0.25
  
dtype: float32 

tokenizer_source: base
