merge_method: task_arithmetic

base_model: ./gpt2-base

models:
  - model: ./wiki-fintuned/model_0
    parameters:
      weight: 0.25

  - model: ./wiki-fintuned/model_1
    parameters:
      weight: 0.25

  - model: ./wiki-fintuned/model_2
    parameters:
      weight: 0.25

  - model: ./wiki-fintuned/model_3
    parameters:
      weight: 0.25
  
dtype: float16 

tokenizer_source: base
