merge_method: task_arithmetic

base_model: ./gpt2-base

models:
  - model: ./bible-finetuned/eng
    parameters:
      weight: 0.1

  - model: ./bible-finetuned/deu
    parameters:
      weight: 0.1

  - model: ./bible-finetuned/fra
    parameters:
      weight: 0.1

  - model: ./bible-finetuned/rus
    parameters:
      weight: 0.1

  - model: ./bible-finetuned/pol
    parameters:
      weight: 0.1

  - model: ./bible-finetuned/cze
    parameters:
      weight:1

  - model: ./bible-finetuned/pt
    parameters:
      weight: 0.1

  - model: ./bible-finetuned/ita
    parameters:
      weight: 0.1

  - model: ./bible-finetuned/bulg
    parameters:
      weight: 0.1

  - model: ./bible-finetuned/spa
    parameters:
      weight: 0.1
  
dtype: float16 

tokenizer_source: base
